CONFIGS = [
    {
        "email": "abc@gmail.com",
        "password": "securepassword",
        "roles": ["backend", "frontend", "full"],
        "skills": [
            "python",
            "javascript",
            "fastapi",
            "mongodb",
            "rabbitmq",
            "react js",
            "node fjs",
            "web scrapping",
        ],
        "locations": [
            "Bangalore",
            "chennai",
            "coimbatore",
            "hyderabad",
            "pune",
            "remote",
        ],
        "experience": 0,
    },
    {
        "email": "abc@gmail.com",
        "password": "securepassword",
        "roles": ["backend", "frontend", "full"],
        "skills": [
            "python",
            "javascript",
            "fastapi",
            "mongodb",
            "rabbitmq",
            "react.js",
            "node.js",
            "web scrapping",
        ],
        "locations": [
            "Bangalore",
            "chennai",
            "coimbatore",
            "hyderabad",
            "pune",
            "remote",
        ],
        "experience": 1,
    },
]
